name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  python-lint-test:
    name: Python lint & tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ "backend", "knowledge", "tracking" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        working-directory: ${{ matrix.module }}
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint (flake8)
        working-directory: ${{ matrix.module }}
        run: flake8 .

      - name: Test (pytest)
        working-directory: ${{ matrix.module }}
        run: pytest

  node-lint-test:
    name: Node lint & tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: middleware
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "middleware/package-lock.json"

      - name: Install
        run: npm ci || npm i

      - name: Lint (eslint)
        run: npm run lint

      - name: Test (jest)
        run: npm test

  docker-build:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: [ python-lint-test, node-lint-test ]
    strategy:
      matrix:
        module:
          - backend
          - middleware
          - knowledge
          - tracking
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ matrix.module }}
        run: docker build -t minecraft-ai-edu/${{ matrix.module }}:ci ./${{ matrix.module }}